version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase

  redis:
    image: redis:latest

  django:
    image: my_django_image
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - django

  celery-worker:
    image: my_celery_image
    depends_on:
      - redis
      - django

  celery-beat:
    image: my_celery_image
    depends_on:
      - redis
      - django
