version: '3.8'

services:
  backend:
    container_name: django
    working_dir: /education
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - static:/education/static
      - media:/education/media
    env_file:
      - ./docker/env/.env.prod
    command: sh -c "python manage.py collectstatic --no-input &&
                    python manage.py makemigrations &&
                    python manage.py migrate &&
                    gunicorn --workers=4 --reload --max-requests=1000 education.wsgi -b 0.0.0.0:8000"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - ./docker/env/.env.prod
    ports:
      - "5432:5432"

  nginx:
    container_name: nginx
    working_dir: /education
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/education/static
      - media:/education/media
      - ./docker/nginx/prod.conf:/etc/nginx/conf.d/django.conf:ro
      - ./docker/certbot/conf:/etc/letsencrypt:ro
      - ./docker/certbot/www:/var/www/certbot:ro

  redis:
    image: redis:alpine
    container_name: redis
    env_file:
      - ./docker/env/.env.prod
    expose:
      - 6379

volumes:
  static:
  media:
  pgdata:


