# Generated by Django 5.0.4 on 2024-07-18 13:26

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('set_courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='full_description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Полное описание'),
        ),
    ]
