# Generated by Django 5.0.4 on 2024-07-18 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_article_count'),
        ('set_courses', '0003_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='module',
            name='article',
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['date', 'time']},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='type',
        ),
        migrations.AddField(
            model_name='schedule',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='course.article'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.TimeField(),
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
