# Generated by Django 5.0.4 on 2024-07-19 09:26

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('set_courses', '0004_remove_schedule_lesson_remove_module_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='full_description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Полное описание'),
        ),
    ]
