# Generated by Django 5.0.4 on 2024-06-19 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-fixed', '-time_create'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
    ]
