# Generated by Django 5.0.4 on 2024-06-20 09:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название вариации')),
                ('description', models.TextField(blank=True, verbose_name='Описание вариации')),
                ('image', models.ImageField(blank=True, upload_to='images/variations/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Изображение вариации')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена вариации')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='course.article')),
            ],
            options={
                'verbose_name': 'Вариация курса',
                'verbose_name_plural': 'Вариации курсов',
            },
        ),
    ]
