# Generated by Django 5.0.4 on 2024-06-25 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_cart_variation'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='teacher.teacher', verbose_name='Преподаватель'),
        ),
    ]
