# Generated by Django 5.0.4 on 2024-06-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_article_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='len_course',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Длительность'),
        ),
        migrations.AddField(
            model_name='article',
            name='start_course',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Начало'),
        ),
    ]
