# Generated by Django 5.0.4 on 2024-07-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_article_len_course_article_start_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество уроков'),
        ),
    ]
