# Generated by Django 5.0.4 on 2024-07-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_article_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='len_course_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длительность курса в мес; нед; днях'),
        ),
    ]
