# Generated by Django 5.0.4 on 2024-07-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_article_len_course_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество уроков'),
        ),
    ]
